version: '3'
services:
  zookeeper_caster:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka_net

  kafka_caster:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper_caster
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_caster:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_caster:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_net

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka_caster:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper_caster:2181
    networks:
      - kafka_net

  caster:
    build:
      context: https://github.com/isatay012or02/kafka-diode-caster.git
      dockerfile: Dockerfile
    environment:
      UDP_ADDRESS: "127.0.0.1:9999"
      TOPICS: "topic1,topic2,topic3"
      ENABLE_HASH: "true"
      DUPLICATES_COUNT: 1
    networks:
      - kafka_net
    restart: always

networks:
  kafka_net:
    driver: bridge
